language: python

sudo: required

group: edge

deploy:
  provider: pages
  # local_dir: ${TRAVIS_BUILD_DIR}/docs/build/html
  local_dir: /docs/build/html
  skip_cleanup: true
  repo: qmlcode/qmlcode.github.io
  target_branch: master
  github_token: ${GH_TOKEN} # Set in travis-ci.org dashboard
  on:
    branch: master
    # condition: ${TRAVIS_PYTHON_VERSION} = "3.6"

python:
  - "3.6"

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc
            - gfortran
            - libblas-dev
            - liblapack-dev
            - gcc-4.8
            - gfortran-4.8
            - pandoc
          update: true

    - os: osx
      osx_image: xcode11
      addons:
        homebrew:
          packages:
          - gcc
          - openblas
          - lapack
          - pandoc
          update: true
      language: shell

install:
 - pip3 install --upgrade pip
 - pip3 install numpy
 - pip3 install scipy
 - pip3 install ase
 - pip3 install pandas
 - pip3 install scikit-learn
 - pip3 install tensorflow
 - pip3 install . 
 - pip3 install sphinx
 - pip3 install nbsphinx
 - pip3 install sphinx-rtd-theme
 - cd ${TRAVIS_BUILD_DIR}/docs
 - make html

before_script:
 - cd ${TRAVIS_BUILD_DIR}/test/

script:
 - pytest -v

notifications:
  email: false
